spring:
  application:
    name: 'consumer_freemarker'

server:
  port: '3000'
  application:
    name: 'consumer_freemarker'
  freemarker:
    request-context-attribute: 'request'
    allow-request-override: 'false'
    allow-session-override: 'false'
    cache: 'false'
    charset: 'UTF-8'
    check-template-location: 'true'
    content-type: 'text/html'
    enabled: 'true'
    expose-request-attributes: 'false'
    expose-session-attributes: 'false'
    expose-spring-macro-helpers: 'true'
    prefer-file-system-access: 'true'
    suffix: '.ftl'
    template-loader-path: 'classpath:/templates/'
    settings.template_update_delay: '0'
    settings.default_encoding: 'UTF-8'
    settings.classic_compatible: 'true'
    order: '1'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:1111/eureka/'

feign:
  httpclient:
    enabled: 'true'

provider:
  ribbon:
    NFLoadBalancerRuleClassName: 'com.netflix.loadbalancer.RandomRule'

logging:
  config: 'classpath:conf/log4j2.xml'